name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: youtube-final

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check build directory
        run: |
          ls -la ./build/libs/

      - name: Upload to S3
        run: |
          jar_file=$(find ./build/libs -name "*.jar" | head -n 1)
          aws s3 cp "$jar_file" "s3://${{ secrets.S3_BUCKET_NAME }}/$PROJECT_NAME/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # 배포 디렉토리 구조 생성
            mkdir -p /home/ubuntu/app/deploy
            
            # S3에서 최신 JAR 파일 정보 확인
            jar_name=$(aws s3 ls "s3://${{ secrets.S3_BUCKET_NAME }}/$PROJECT_NAME/" | sort | tail -n 1 | awk '{print $4}')
            timestamp=$(date +%Y%m%d_%H%M%S)
            deploy_dir="/home/ubuntu/app/deploy/$timestamp"
            
            # 새로운 배포 디렉토리 생성 및 JAR 파일 다운로드
            mkdir -p $deploy_dir
            aws s3 cp "s3://${{ secrets.S3_BUCKET_NAME }}/$PROJECT_NAME/$jar_name" "$deploy_dir/application.jar"
            
            # 기존 프로세스 종료
            sudo pkill -f "$PROJECT_NAME" || true
            
            # 새 JAR 파일 실행
            cd $deploy_dir
            nohup java -jar application.jar --spring.profiles.active=aws > application.log 2>&1 &
            
            # 심볼릭 링크 업데이트
            ln -sfn $deploy_dir /home/ubuntu/app/current
            
            # 이전 버전 정리 (최근 3개 버전만 유지)
            cd /home/ubuntu/app/deploy && ls -t | tail -n +4 | xargs rm -rf