name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Make zip file
        run: zip -r ./deploy.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app
            sudo rm -rf ./deploy
            mkdir ./deploy
            cd ./deploy
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip .
            unzip ./deploy.zip
            sudo chmod +x ./gradlew
            sudo ./gradlew clean build -x test
            cd build/libs
            
            # 기존 프로세스 종료
            CURRENT_PID=$(pgrep -f '.jar')
            if [ -n "$CURRENT_PID" ]; then
              echo "Kill process id: $CURRENT_PID"
              sudo kill -15 $CURRENT_PID
              sleep 5
            
              # SIGTERM 후에도 프로세스가 살아있다면 SIGKILL
              if ps -p $CURRENT_PID > /dev/null; then
                sudo kill -9 $CURRENT_PID
              fi
            fi
            
            # 새 프로세스 시작 (메모리 설정 추가)
            nohup java -jar \
              -Dspring.profiles.active=aws \
              -Xms512m -Xmx1024m \
              -XX:+HeapDumpOnOutOfMemoryError \
              -XX:HeapDumpPath=/home/ubuntu/app/heapdump.hprof \
              *.jar > /home/ubuntu/app/application.log 2>&1 &
            
            echo "Deploy finished"