name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: youtube-final

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp \
          ./build/libs/*.jar \
          s3://${{ secrets.S3_BUCKET_NAME }}/$PROJECT_NAME/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # S3에서 JAR 파일 다운로드
            aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/$PROJECT_NAME/$(ls /s3/$PROJECT_NAME/ | grep .jar) /home/${{ secrets.EC2_USERNAME }}/app/
            
            # 기존 애플리케이션 중지
            sudo systemctl stop $PROJECT_NAME || true
            
            # 새 JAR 파일로 서비스 실행 (aws 프로파일 사용)
            sudo java -jar /home/${{ secrets.EC2_USERNAME }}/app/*.jar --spring.profiles.active=aws &