name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JAR to S3
        run: |
          aws s3 cp build/libs/youtube-0.0.1-SNAPSHOT.jar "s3://${{ secrets.S3_BUCKET_NAME }}/youtube.jar"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Downloading JAR from S3..."
            aws s3 cp "s3://${{ secrets.S3_BUCKET_NAME }}/youtube.jar" /home/ubuntu/app/application.jar
            sudo chown ubuntu:ubuntu /home/ubuntu/app/application.jar
            
            echo "Starting application..."
            cd /home/ubuntu/app
            sudo systemctl stop spring-app
            
            sudo -E java -jar application.jar \
            --spring.profiles.active=aws \
            --spring.output.ansi.enabled=never \
            --spring.datasource.url=jdbc:mariadb://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
            --spring.datasource.username=${{ secrets.DB_USERNAME }} \
            --spring.datasource.password=${{ secrets.DB_PASSWORD }} \
            --cloud.aws.s3.bucket=${{ secrets.S3_BUCKET_NAME }} \
            --cloud.aws.credentials.access-key=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --cloud.aws.credentials.secret-key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --cloud.aws.region.static=${{ secrets.AWS_REGION }}